import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { Suspense } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gradient-to-r from-teal-100 to-blue-200`}
      >
      <header className="absolute top-4 left-4 z-10 flex flex-col space-y-4 items-center pl-1">
    {/* Skoggy Link */}
    <div className="relative flex items-center group">
      <Link href="/">
        <Image
          src="/images/skoggy.png"
          alt="Skoggy Logo"
          width={40}
          height={40}
          className="rounded-full peer hover:scale-110 transition-all duration-300"
        />
      </Link>
      <span className="absolute font-mono left-[3rem] opacity-0 scale-x-0 group-hover:scale-x-100 group-hover:opacity-100 origin-left transition-all duration-300 ml-2 text-teal-700 font-semibold">
        Home
      </span>
    </div>

    {/* Contact Link */}
    <div className="relative flex items-center group">
      <Link href="/contact">
        <Image
          src="/images/contact.png"
          alt="Contact"
          width={40}
          height={40}
          className="rounded-full peer-hover:translate-x-4 hover:scale-110 transition-all duration-300"
        />
    </Link>
    <span className="absolute font-mono left-[3rem] opacity-0 scale-x-0 group-hover:scale-x-100 group-hover:opacity-100 origin-left transition-all duration-300 ml-2 text-teal-700 font-semibold">
      Contact
    </span>
  </div>
</header>
  <Suspense fallback={<div>Loading...</div>}>
    {children}
  </Suspense>
      </body>
    </html>
  );
}
